### ISSUE TITLE
Nuget Package Name and Installation Instructions

### ISSUE THREAD

**Issue by stonstad** [Microsoft/xbox-live-api-csharp#55]
Thank you for contributing this library.  Beyond compiling from source it isn't clear how to install the library.  Is there a nuget package -- what is it's name?  Could we place this information in the README file?  Keep up the awesome work.

**Comment by veleek** [comment]
@stonstad: Yes, we still have some work to do to make this easy to consume.  We have not created a NuGet package but we have plans to do so in the near future.  We can keep this bug open to track the status of that.  

Compiling from source is the only option at the moment but I'll try to get a set of binaries pushed to the GitHub release next week so their available while we get the NuGet package ready.

**Comment by stonstad** [comment]
Thanks @veleek for the quick response.  I was able to build and run from source successfully.  Thanks!
