### ISSUE TITLE
ProfileService Can't Be Created?

### ISSUE THREAD

**Issue by stonstad** [Microsoft/xbox-live-api-csharp#56]
ProfileService has an internal constructor and there no classes in the C# library which provide a factory create method.  I checked XboxLiveContext and this class does not have a method for creating an instance either.  For this reason it appears that it may not possible to access a user's profile in the C# XBOX Live API.

**Comment by veleek** [comment]
The ProfileService is intended to be consumed through the SocialManager interface.  SocialManager handles automatically querying the ProfileService and caching the results for you and keeping everything up to date in the background.  

I'm marking this as closed but let me know if you feel it should be reopened for any reason.

**Comment by stonstad** [comment]
I appreciate your response -- I'm good if it isn't meant to be accessed directly.  I'm struggling to find some documentation to show how I might access the user profile which contains the gamer pic.  I see that it is in XboxUserProfile which ProfileService creates.  Thanks again for your help.

**Comment by veleek** [comment]
Take a look at the UserProfile script in the Unity Plugin (https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/UserProfile.cs#L77)  This uses SocialManager to get the profile information for the signed in user.  

Yes, it is currently much more complicated then it needs to be, but this will allow you to get the image easily.

**Comment by stonstad** [comment]
Yeah, the API isn't as direct as it could be.  When I try this... I can authenticate and get an XboxUser but the above code causes the live server to throw this error: : The remote server returned an error: (401) Unauthorized.

I haven't ruled out user error on my part -- not sure what would cause getting the XboxSocialUser through the SocialManager to fail.  I'm switched to the right environment and my account is added as a test user.  It works fine on my XB1 in dev mode but fails on Windows 10 desktop.

**Comment by veleek** [comment]
@stonstad Hmmm... if you're getting a 401 that's because of a problem with the auth token.  It should affect every single API the same way.  It looks like you can attach files to this issue.  If you're still having trouble you can attach a Fiddler trace to help us narrow down the issue.
