### ISSUE TITLE
Unable To Build Project in Visual Studio 15 u3

### ISSUE THREAD

**Issue by Eversor** [Microsoft/xbox-live-api-csharp#59]
I'm trying to build the project in Visual Studio 15 but i got a lot of errors and incompatibilities.
Is there any way to allow building the project in vs15?

**Comment by veleek** [comment]
We use Visual Studio 15 internally so it should build fine.  You may be running into compatibility issues with the Unity build portion.  You can try either unloading the Microsoft.Xbox.Services.UnityEditor project or installing Unity. 

If that's not the problem can you provide more information about your error?

**Comment by Eversor** [comment]
Seems like it solved itself during the install of visual studio 2017... I wish i could give you more infos but atm i think this can be closed...

**Comment by MrZweistein** [comment]
It seems to me it may related to the fact that the latest SDK is part of the 2017 package while with 2015 you have to install it on your own afaik.

**Comment by veleek** [comment]
Yeah, that's definitely a possible source of failure.  Closing for now, feel free to ask for re-open.

**Comment by Eversor** [comment]
Still having troubles on a different pc with VS2015 installed : 

now i get a compiler error giving **'XboxLiveContextSettings' could not be found**. 

I tried updating the Microsoft.NETCore.UniversalWindowsPlatform nuget used by the main project but i cannot get any higher than 5.2.3.
I also tried to manually update Windows 10 Sdk to latest version.

**Comment by MrZweistein** [comment]
Are you sure you setup the xboxservices.config file to copy always when the application is deployed?

**Comment by adityatMS** [comment]
Sorry about the build break. I've checked in a fix to resolve the **'XboxLiveContextSettings' could not be found** compile issue. Can you fetch the latest and try again?

**Comment by Eversor** [comment]
This is now working properly thanks.
