### ISSUE TITLE
Failing in a simple SigninSilently->UserInteractionRequired->Signin Loop (possible config issue)

### ISSUE THREAD

**Issue by Eversor** [Microsoft/xbox-live-api-csharp#65]
I'm trying to authenticate my user to try some achievement settings, but using this loop the xbox continues opening the dashboard returning "UserInteractionRequired" even after a user.SignInAsync() call.

From my understanding of the docs, this should never happen (see XBLiveSDK.ch->XBL Programming Guide->Using Xbox Live->Authentication for UWP).

        protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            user = new Microsoft.Xbox.Services.XboxLiveUser();
            user.SignInSilentlyAsync().ContinueWith(signinCompleted);
            //{...}
        }
        private void signinCompleted(Task<SignInResult> result)
        {
            var signin_result = result.Result;
            switch (signin_result.Status)
            {
                case SignInStatus.Success:
                    System.Diagnostics.Debug.WriteLine($"Login Succeded, user gamertag is : {user.Gamertag}");
                    break;
                case SignInStatus.UserInteractionRequired:
                    System.Diagnostics.Debug.WriteLine($"Login USER INTERACTION REQUIRED");
                    user.SignInAsync().ContinueWith(signinCompleted);
                    break;
                case SignInStatus.UserCancel: // OR SinginError
                default:
                    System.Diagnostics.Debug.WriteLine($"Login FAILED");
                    break;
            }
        }

**Comment by adityatMS** [comment]
You should ideally see an error message with an error code in the UI dialog box. Are you seeing any exceptions or debug spew in your debug output window?

A few things to check:
- Are you using a test pfx to sign the appx? Try replacing it with the real pfx from windows store (right click on project, select store->associate app with store).
- Make sure you are signed into the correct sandbox for your app.
- Ensure you have xboxservices.config setup correctly.

**Comment by Eversor** [comment]
Unfortunately no error is displayed in debug output, and the window on the xbox appears for just a second and then closes. 
Since you mentioned it, i did the store-association thing. 
My XboxServices.config reads:
{
"TitleId": 999999999, //<---- TitleId Int form from XDP Product Details
"PrimaryServiceConfigId": "0f000000-0000-0000-f000-00ff0f00f0f0" //<---- SCID form from XDP Product Details
}

**Comment by Eversor** [comment]
As an update, it seems like a provider error is raised and then somehow promoted to InteractionRequested.
I'm currently tracking the problem to a missing error log at line 372 of UserImpl.cs

**Comment by jicailiu** [comment]
Looks like a bug from us. We will address it.

**Comment by Eversor** [comment]
Thank you @jicailiu

**Comment by jicailiu** [comment]
https://github.com/Microsoft/xbox-live-api-csharp/pull/71 should fixed the issue. Now provider error will cause throwing exception.
