### ISSUE TITLE
Unable to copy Newtonsoft.Json.9.0.1 (wrong path?)

### ISSUE THREAD

**Issue by Eversor** [Microsoft/xbox-live-api-csharp#68]
The build process breaks at the step where it tries to xcopy the NewtonSoft.Json dll.
I had to manually place the file from my "c:\Users\{user}\.nuget\packages folder to the required folder before being able to build. 
Don't know if this is intended behaviour but manual copying works so it might be useful for other people intending to solve the issue.

**Comment by veleek** [comment]
Can you provide a bit of clarification around the error that you're seeing?  I don't have any issues with the build on my machine.

**Comment by Eversor** [comment]
If there is some custom code copying the newtonsoft.json to the output directory during build, then on one of my machines it failed due to the dll already being in the package cache (thus in a different folder). I'm not 100% sure this is directly related to this project.

**Comment by veleek** [comment]
When the Microsoft.Xbox.Services.UWP.CSharp project builds, it runs an additional target `LayoutPlugin` that copies the binaries to a specific output folder.  Unfortunately, due to the way UWP libs build it doesn't copy dependent assemblies into the output folder so instead we attempt to copy it from the packages folder.  So yeah, if Newtonsoft.Json.dll is being grabbed from elsewhere you could see a failure.

```xml
  <Target Name="LayoutPlugin" AfterTargets="Build">
    <Message Importance="high" Text="OutputPath: $(OutDir)" />
    <Message Importance="high" Text="Copying binaries to plugin layout path $(PluginLayoutPath)" />
    <MakeDir Directories="$(PluginLayoutPath)" />
    <Exec Command="xcopy /y /d $(OutDir)*.dll $(PluginLayoutPath)" />
    <Exec Command="xcopy /y /d $(OutDir)*.pdb $(PluginLayoutPath)" Condition="'$(Configuration)' == 'Debug'" />
    <Exec Command="xcopy /y /d $(ProjectDir)..\packages\Newtonsoft.Json.9.0.1\lib\portable-net45+wp80+win8+wpa81\Newtonsoft.Json.dll $(PluginLayoutPath)" />
  </Target>
```

**Comment by jasonsandlin** [comment]
We'll internally track this bug as we're shutting down this repo in favor of https://github.com/Microsoft/xbox-live-unity-plugin
