### ISSUE TITLE
Login UI not showing and immediately returns "ProviderError"

### ISSUE THREAD

**Issue by Eversor** [Microsoft/xbox-live-api-csharp#73]
When running the UserImpl.RequestTokenFromIdpAsync with promptForCredentialsIfNeeded=true,
the console shows the system UI for just an instant and then closes. 

When inspecting the 
WebTokenRequestResult result at line 263,

I get this ProviderError:

ErrorCode = 2148734217
ErrorMessage = "Unexpected response code: Unknown"

**Comment by jicailiu** [comment]
What version of OS are you on?

**Comment by Eversor** [comment]
![immagine](https://cloud.githubusercontent.com/assets/733699/25274320/d4348fc8-268f-11e7-90a9-c3c2f4caa5c5.png)

**Comment by jicailiu** [comment]
It looks like something goes wrong with console OS, and it failed to populate the detailed error code to us. We don't own the OS component, but we can help escalate the issue if we have more details. 

Can you try following things:
- Can you run your app on PC to see if it make any difference? 
- Does reboot console solve the issue?

**Comment by jasonsandlin** [comment]
If you are still having troubles, feel free to post a question here: https://social.msdn.microsoft.com/Forums/en-US/home?forum=xboxlivedev&filter=unanswered
